import { getProgress } from "./tracker.js";
import { ChecklistCategory, ItemStatus } from "./types.js";

const categoryLabels: Record<ChecklistCategory, string> = {
  [ChecklistCategory.PREBOARDING]: "Preboarding",
  [ChecklistCategory.DAY_ONE]: "Day One",
  [ChecklistCategory.FIRST_WEEK]: "First Week",
  [ChecklistCategory.FIRST_MONTH]: "First Month",
  [ChecklistCategory.COMPLIANCE]: "Compliance",
  [ChecklistCategory.TOOLS_ACCESS]: "Tools & Access",
  [ChecklistCategory.TEAM_INTEGRATION]: "Team Integration",
};

function progressBar(percentage: number, width = 20): string {
  const filled = Math.round((percentage / 100) * width);
  const empty = width - filled;
  return `[${"█".repeat(filled)}${"░".repeat(empty)}] ${percentage}%`;
}

export function generateProgressReport(trackerPath: string): string {
  const progress = getProgress(trackerPath);
  const lines: string[] = [];

  lines.push(`# Onboarding Progress Report: ${progress.hireeName}`);
  lines.push(`_Generated: ${new Date().toISOString().split("T")[0]}_`);
  lines.push("");

  lines.push("## Overall Progress");
  lines.push("");
  lines.push(progressBar(progress.completionPercentage));
  lines.push("");
  lines.push(`| Status | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Completed | ${progress.completed} |`);
  lines.push(`| In Progress | ${progress.inProgress} |`);
  lines.push(`| Pending | ${progress.pending} |`);
  lines.push(`| Blocked | ${progress.blocked} |`);
  lines.push(`| Skipped | ${progress.skipped} |`);
  lines.push(`| **Total** | **${progress.totalItems}** |`);
  lines.push("");

  lines.push("## Progress by Category");
  lines.push("");
  for (const [cat, stats] of Object.entries(progress.categoryBreakdown)) {
    const label = categoryLabels[cat as ChecklistCategory] ?? cat;
    if (stats.total === 0) continue;
    lines.push(`### ${label}`);
    lines.push(progressBar(stats.percentage));
    lines.push(`${stats.completed}/${stats.total} items completed`);
    lines.push("");
  }

  if (progress.overdueItems.length > 0) {
    lines.push("## Overdue Items");
    lines.push("");
    lines.push("| Item | Owner | Target Day | Status |");
    lines.push("|------|-------|------------|--------|");
    for (const item of progress.overdueItems) {
      const statusLabel = item.status === ItemStatus.BLOCKED ? "BLOCKED" : "OVERDUE";
      lines.push(`| ${item.title} | ${item.owner} | Day ${item.dayTarget} | ${statusLabel} |`);
    }
    lines.push("");
  }

  if (progress.upcomingMilestones.length > 0) {
    lines.push("## Upcoming Milestones");
    lines.push("");
    for (const milestone of progress.upcomingMilestones) {
      lines.push(`- **${milestone.name}** — Target: Day ${milestone.targetDay}`);
    }
    lines.push("");
  }

  if (progress.blocked > 0 || progress.overdueItems.length > 0 || progress.completionPercentage < 50) {
    lines.push("## Action Items");
    lines.push("");
    if (progress.blocked > 0) {
      lines.push(`- Resolve ${progress.blocked} blocked item(s) — check dependencies and owners`);
    }
    if (progress.overdueItems.length > 0) {
      lines.push(`- Follow up on ${progress.overdueItems.length} overdue item(s)`);
    }
    if (progress.completionPercentage < 50) {
      lines.push("- Overall completion below 50% — consider reviewing workload with manager");
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("_Report generated by Employee Onboarding Automator_");

  return lines.join("\n");
}

